(define (double f) (lambda (x) (f (f x))))
(define (inc x) (+ x 1))
(define (id f) f)
(newline)
(newline)
(display "(((double (double double)) inc) 5) = ")
(display (((double (double double)) inc) 5))
(newline)
(newline)
(exit)